from pathlib import Path
import unittest
from spiritstream.tree import treeify, tokenize, walk, serialize, tokenizeCSS, show, parse, css_to_dict, Status, K
from spiritstream.helpers import SPACES

TEST_CASES = [
    {
        "name": "emptylines",
        "md": "\n\n\t   \n",
        "tokens": [{"name":"empty_line"}] * 4,
        "nodes": [{"name":K.BODY}] + [{"name":K.EMPTY_LINE}] * 4,
    },
    {
        "name": "heading",
        "md": "#no heading\n# heading\n## heading\n###### heading\n####### heading\n \t# no heading",
        "tokens": [{"name": "paragraph_line"},
            {"name": "heading","data": 1},
            {"name": "heading","data": 2},
            {"name": "heading","data": 6},
            {"name": "heading","data": 7}],
        "nodes": [{"name": K.BODY},
            {"name": K.P},
            {"name": K.H1},
            {"name": K.H2},
            {"name": K.H6},
            {"name": K.H6}],
    },
    {
        "name": "codeblock",
        "md": "hamedi\n~~~language line\n# no heading\n~~~\n``\n``` language \n\tcode\n```\n",
        "tokens": [{"name": "paragraph_line"},
            {"name":"codeblock", "data": ("language line", 16)},
            {"name": "paragraph_line"},
            {"name":"double_inline_code"},
            {"name": "codeblock", "data": ("language", 13)}],
        "nodes": [{"name": K.BODY},
            {"name": K.P},
            {"name": K.CODE, "data": {"language": "language line"}},
            {"name": K.P},
            {"name": K.P},
            {"name": K.P},
            {"name": K.CODE, "data": {"language": "language"}},
            {"name": K.P},
            {"name": K.P}]
    },
    {
        "name": "horizontal rule *_",
        "md": [s:="\n***\n**\n****\n*****  \n* * *\n** * ** \n   **     *\n* **\n    ***\n     * **", s.replace("*", "_")],
        "tokens": [{"name:" "empty_line"},
            {"name": "horizontal_rule"},
            {"name": "paragraph_line"},
            {"name": "horizontal_rule"},
            {"name": "horizontal_rule"},
            {"name": "horizontal_rule"},
            {"name": "horizontal_rule"},
            {"name": "horizontal_rule"},
            {"name": "horizontal_rule"}],
        "nodes": [{"name": K.BODY},
            {"name": K.EMPTY_LINE},
            {"name": K.HR},
            {"name": K.P},
            {"name": K.HR},
            {"name": K.HR},
            {"name": K.HR},
            {"name": K.HR},
            {"name": K.HR},
            {"name": K.HR},
            {"name": K.CODE}]
    },
    {
    "name": "horizontal rule -",
    "md": "\n***\n**\n****\n*****  \n* * *\n** * ** \n   **     *\n* **\n    ***\n     * **".replace("*", "-"),
    "tokens": [{"name:" "empty_line"},
        {"name": "horizontal_rule"},
        {"name": "paragraph_line"},
        {"name": "horizontal_rule"},
        {"name": "horizontal_rule"},
        {"name": "horizontal_rule"},
        {"name": "horizontal_rule"},
        {"name": "horizontal_rule"},
        {"name": "horizontal_rule"}],
    "nodes": [{"name": K.BODY},
        {"name": K.EMPTY_LINE},
        {"name": K.HR},
        {"name": K.P},
        {"name": K.HR},
        {"name": K.HR},
        {"name": K.HR},
        {"name": K.HR},
        {"name": K.HR},
        {"name": K.HR},
        {"name": K.CODE}]
    },
    {
        "name": "blockquote",
        "md": "> hamedi1\n    > hamedi2\n> hamedi3\n>> hamedi4\n>> hamedi5\n >hamid\n \\>hamud\n",
        "tokens": [{"name": "blockquote_line", "data": 1},
            {"name": "indented_line"},
            {"name": "blockquote_line", "data":1},
            {"name": "blockquote_line", "data":2},
            {"name": "blockquote_line", "data":2},
            {"name": "blockquote_line", "data":1},
            {"name": "paragraph_line"}],
        "nodes": [{"name": K.BODY},
            {"name": K.BLOCKQUOTE, "data": {"depth": 1}},
            {"name": K.CODE},
            {"name": K.BLOCKQUOTE, "data": {"depth": 1}},
            {"name": K.BLOCKQUOTE, "data": {"depth": 2}},
            {"name": K.P}],
    },
    {
        "name": "unordered list",
        "md": "hamedi\n- hamedi2\n- hamedi3\n    hamedi4\n\n    - hamedi5",
        "tokens": [{"name": "paragraph_line"},
            {"name": "listitem", "data": (0, K.UL, None)},
            {"name": "listitem", "data": (0, K.UL, None)},
            {"name": "indented_line", "data": 4},
            {"name": "empty_line"},
            {"name": "listitem", "data": (4, K.UL, None)}],
        "nodes": [{"name": K.BODY},
            {"name": K.P},
            {"name": K.UL, "data": {"indent": 0}},
            {"name": K.LI, "data": {"digit": None}},
            {"name": K.LI, "data": {"digit": None}},
            {"name": K.CODE},
            {"name": K.EMPTY_LINE},
            {"name": K.CODE}]
    },
    {
        "name": "ordered list",
        "md": "1. hamid\n001. hamedi\n-2. invalid\n4. hamedi2\n. hamedi3\n\n11. hamedii\n    15.         hamedi",
        "tokens": [{"name": "listitem", "data": (0, K.OL, 1)},
            {"name": "listitem", "data": (0, K.OL, 1)},
            {"name": "paragraph_line"},
            {"name": "listitem", "data": (0, K.OL, 4)},
            {"name": "paragraph_line"},
            {"name": "empty_line"},
            {"name": "listitem", "data": (0, K.OL, 11)},
            {"name": "listitem", "data": (4, K.OL, 15)}],
        "nodes": [{"name": K.BODY},
            {"name": K.OL, "data": {"indent": 0}},
            {"name": K.LI, "data": {"digit": 1}},
            {"name": K.LI, "data": {"digit": 1}},
            {"name": K.P},
            {"name": K.OL, "data": {"indent": 0}},
            {"name": K.LI, "data": {"digit": 4}},
            {"name": K.P},
            {"name": K.EMPTY_LINE},
            {"name": K.OL, "data": {"indent": 0}},
            {"name": K.LI, "data": {"digit": 11}},
            {"name": K.OL, "data": {"indent": 4}},
            {"name": K.LI, "data": {"digit": 15}}]
    },
    {
        "name": "mixed_list",
        "md": "1. hamedi\n- hamid\n2. hamedi\n\t1. hamedi2\n- hamedi0\n\n\t- hamedi0\n2. hamedi2\n\n\t- hamedi",
        "tokens": [{"name": "listitem", "data": (0, K.OL, 1)},
            {"name": "listitem", "data": (0, K.UL, None)},
            {"name": "listitem", "data": (0, K.OL, 2)},
            {"name": "listitem", "data": (SPACES, K.OL, 1)},
            {"name": "listitem", "data": (0, K.UL, None)},
            {"name": "empty_line"},
            {"name": "listitem", "data": (SPACES, K.UL, None)},
            {"name": "listitem", "data": (0, K.OL, 2)},
            {"name": "empty_line"},
            {"name": "listitem", "data": (SPACES, K.UL, None)}],
        "nodes": [{"name": K.BODY},
            {"name": K.OL, "data": {"indent": 0}},
            {"name": K.LI},
            {"name": K.UL, "data": {"indent": 0}},
            {"name": K.LI},
            {"name": K.OL, "data": {"indent": 0}},
            {"name": K.LI},
            {"name": K.OL, "data": {"indent": 4}},
            {"name": K.LI},
            {"name": K.UL, "data": {"indent": 0}},
            {"name": K.LI},
            {"name": K.EMPTY_LINE},
            {"name": K.CODE},
            {"name": K.OL, "data": {"indent": 0}},
            {"name": K.LI},
            {"name": K.EMPTY_LINE},
            {"name": K.CODE},
            ]
    },
    {
        "name": "indented line",
        "md": "\n#hamedi0\n   #hamedi1\n    #hamedi2.5\n\t# hamedi2\n \t# hamedi3\n\t**hamedi**",
        "tokens": [{"name": "empty_line"},
            {"name": "paragraph_line"},
            {"name": "paragraph_line"},
            {"name": "indented_line", "data": 4},
            {"name": "indented_line", "data": 4},
            {"name": "indented_line", "data": 5},
            {"name": "indented_line", "data": 4}],
        "nodes": [{"name": K.BODY},
            {"name": K.EMPTY_LINE},
            {"name": K.P},
            {"name": K.CODE}]
    },
    {
        "name": "paragraph",
        "md": "p\nparagraph2 multiword\n   indented slightly\n    indented too much\n    \np\n# not a paragraph\n**paragraph**\n   ",
        "tokens": [{"name": "paragraph_line"},
            {"name": "paragraph_line"},
            {"name": "paragraph_line"},
            {"name": "indented_line", "data": 4},
            {"name": "empty_line"},
            {"name": "paragraph_line"},
            {"name": "heading", "data": 1},
            {"name": "paragraph_line"}],
        "nodes": [{"name": K.BODY},
            {"name": K.P},
            {"name": K.CODE},
            {"name": K.EMPTY_LINE},
            {"name": K.P},
            {"name": K.H1},
            {"name": K.P}],
    },
    {
        "name": "italic",
        "md": [s:="hamedi*\nhamedi*is*here\n*hamedi* is here\nhamedi*\nis* here\nhamedi * is * here\nhamedi *is* here\nhamedi *is * here\nham*edi*\n***", s.replace("*", "_")],
        "tokens": [{"name": "paragraph_line"},
            {"name": "italic_end"},
            {"name": "paragraph_line"},
            {"name": "italic_toggle"},
            {"name": "italic_toggle"},
            {"name": "paragraph_line"},
            {"name": "italic_start"},
            {"name": "italic_end"},
            {"name": "paragraph_line"},
            {"name": "italic_end"},
            {"name": "paragraph_line"},
            {"name": "italic_end"},
            {"name": "paragraph_line"},
            {"name": "paragraph_line"},
            {"name": "italic_start"},
            {"name": "italic_end"},
            {"name": "paragraph_line"},
            {"name": "italic_start"},
            {"name": "paragraph_line"},
            {"name": "italic_toggle"},
            {"name": "italic_end"},
            {"name": "horizontal_rule"}],
        "nodes": [{"name": K.BODY},
            {"name": K.P},
            {"name": K.I},
            {"name": K.I},
            {"name": K.I},
            {"name": K.I},
            {"name": K.I},
            {"name": K.HR}]
    },
    {
        "name": "bold",
        "md": [s:="hamedi*\nhamedi*is*here\n*hamedi* is here\nhamedi*\nis* here\nhamedi * is * here\nhamedi *is* here\nhamedi *is * here\nham*edi*\n***".replace("*", "**"), s.replace("*", "_")],
        "tokens": [{"name": "paragraph_line"},
            {"name": "bold_end"},
            {"name": "paragraph_line"},
            {"name": "bold_toggle"},
            {"name": "bold_toggle"},
            {"name": "paragraph_line"},
            {"name": "bold_start"},
            {"name": "bold_end"},
            {"name": "paragraph_line"},
            {"name": "bold_end"},
            {"name": "paragraph_line"},
            {"name": "bold_end"},
            {"name": "paragraph_line"},
            {"name": "paragraph_line"},
            {"name": "bold_start"},
            {"name": "bold_end"},
            {"name": "paragraph_line"},
            {"name": "bold_start"},
            {"name": "paragraph_line"},
            {"name": "bold_toggle"},
            {"name": "bold_end"},
            {"name": "horizontal_rule"}],
        "nodes": [{"name": K.BODY},
            {"name": K.P},
            {"name": K.B},
            {"name": K.B},
            {"name": K.B},
            {"name": K.B},
            {"name": K.B},
            {"name": K.HR}]
    },
    {
        "name": "bolditalic",
        "md": [s:="hamedi*\nhamedi*is*here\n*hamedi* is here\nhamedi*\nis* here\nhamedi * is * here\nhamedi *is* here\nhamedi *is * here\nham*edi*\n***".replace("*", "***"), s.replace("*", "_")],
        "tokens": [{"name": "paragraph_line"},
            {"name": "bolditalic_end"},
            {"name": "paragraph_line"},
            {"name": "bolditalic_toggle"},
            {"name": "bolditalic_toggle"},
            {"name": "paragraph_line"},
            {"name": "bolditalic_start"},
            {"name": "bolditalic_end"},
            {"name": "paragraph_line"},
            {"name": "bolditalic_end"},
            {"name": "paragraph_line"},
            {"name": "bolditalic_end"},
            {"name": "paragraph_line"},
            {"name": "paragraph_line"},
            {"name": "bolditalic_start"},
            {"name": "bolditalic_end"},
            {"name": "paragraph_line"},
            {"name": "bolditalic_start"},
            {"name": "paragraph_line"},
            {"name": "bolditalic_toggle"},
            {"name": "bolditalic_end"},
            {"name": "horizontal_rule"}],
        "nodes": [{"name": K.BODY},
            {"name": K.P},
            {"name": K.BI},
            {"name": K.BI},
            {"name": K.BI},
            {"name": K.BI},
            {"name": K.BI},
            {"name": K.HR}]
    },
    {
        "name": "strikethrough",
        "md": "hamedi~~\nhamedi~~is~~here\n~~hamedi~~ is here\nhamedi~~\nis~~ here\nhamedi ~~ is ~~ here\nhamedi ~~is~~ here\nhamedi ~~is ~~ here\nham~~edi~~\n~~~~~~",
        "tokens": [{"name": "paragraph_line"},
            {"name": "strikethrough_end"},
            {"name": "paragraph_line"},
            {"name": "strikethrough_toggle"},
            {"name": "strikethrough_toggle"},
            {"name": "paragraph_line"},
            {"name": "strikethrough_start"},
            {"name": "strikethrough_end"},
            {"name": "paragraph_line"},
            {"name": "strikethrough_end"},
            {"name": "paragraph_line"},
            {"name": "strikethrough_end"},
            {"name": "paragraph_line"},
            {"name": "paragraph_line"},
            {"name": "strikethrough_start"},
            {"name": "strikethrough_end"},
            {"name": "paragraph_line"},
            {"name": "strikethrough_start"},
            {"name": "paragraph_line"},
            {"name": "strikethrough_toggle"},
            {"name": "strikethrough_end"},
            {"name": "paragraph_line"}],
        "nodes": [{"name": K.BODY},
            {"name": K.P},
            {"name": K.S},
            {"name": K.S},
            {"name": K.S},
            {"name": K.S},
            {"name": K.S}]
    },
    {
        "name": "wikilinks",
        "md": "[[hamedi0]]\n![[hamedi1]]\n\\![[hamedi2]]\n\\[hamedi3]\n\\[[hamedi4]]\n[[hamedi5]][[hamedi6]]\n[![ha]]\n[[hamedi7][hamedi8]]\n[[hamedi9]](breaking?)\n\\]]\n]\\]",
        "tokens": [{"name": "paragraph_line"},
            {"name": "wikilink_start"},
            {"name": "wikilink_end"},
            {"name": "paragraph_line"},
            {"name": "wikilink_embed_start"},
            {"name": "wikilink_end"},
            {"name": "paragraph_line"},
            {"name": "wikilink_start"},
            {"name": "wikilink_end"},
            {"name": "paragraph_line"},
            {"name": "paragraph_line"},
            {"name": "markdownlink_start"},
            {"name": "wikilink_end"},
            {"name": "paragraph_line"},
            {"name": "wikilink_start"},
            {"name": "wikilink_end"},
            {"name": "wikilink_start"},
            {"name": "wikilink_end"},
            {"name": "paragraph_line"},
            {"name": "markdownlink_start"},
            {"name": "markdownlink_embed_start"},
            {"name": "wikilink_end"},
            {"name": "paragraph_line"},
            {"name": "wikilink_start"},
            {"name": "markdownlink_start"},
            {"name": "wikilink_end"},
            {"name": "paragraph_line"},
            {"name": "wikilink_start"},
            {"name": "wikilink_end"},
            {"name": "opening_parenthesis"},
            {"name": "closing_parenthesis"}],
        "nodes": [{"name": K.BODY},
            {"name": K.P},
            {"name": K.A, "data": {"linktype": "wiki"}},
            {"name": K.IMG, "data": {"linktype": "wiki"}},
            {"name": K.A, "data": {"linktype": "wiki"}},
            {"name": K.A, "data": {"linktype": "wiki"}},
            {"name": K.A, "data": {"linktype": "wiki"}},
            {"name": K.A, "data": {"linktype": "wiki"}},
            {"name": K.A, "data": {"linktype": "wiki"}}]
    },
    {
        "name": "markdown_links",
        "md": "[[hamedi1](hamedi2)]\n[hamedi3](hamedi4)\n    (hamedi5)[hamedi6]\n    [hamedi7\\](hamedi8)\n\\[[hamedi9](omedi)]]\n[ham[edi]](hamudi)\n![hamediembed](here)\n![hamediembed1invalid]\n[](",
        "tokens": [{"name": "paragraph_line"},
            {"name": "wikilink_start"},
            {"name": "markdownlink_switch"},
            {"name": "closing_parenthesis"},
            {"name": "paragraph_line"},
            {"name": "markdownlink_start"},
            {"name": "markdownlink_switch"},
            {"name": "closing_parenthesis"},
            {"name": "indented_line", "data": 4},
            {"name": "indented_line", "data": 4},
            {"name": "paragraph_line"},
            {"name": "markdownlink_start"},
            {"name": "markdownlink_switch"},
            {"name": "closing_parenthesis"},
            {"name": "wikilink_end"},
            {"name": "paragraph_line"},
            {"name": "markdownlink_start"},
            {"name": "markdownlink_start"},
            {"name": "wikilink_end"},
            {"name": "opening_parenthesis"},
            {"name": "closing_parenthesis"},
            {"name": "paragraph_line"},
            {"name": "markdownlink_embed_start"},
            {"name": "markdownlink_switch"},
            {"name": "closing_parenthesis"},
            {"name": "paragraph_line"},
            {"name": "markdownlink_embed_start"}],
        "nodes": [{"name": K.BODY},
            {"name": K.P},
            {"name": K.A, "data": {"linktype": "md switched"}},
            {"name": K.A, "data": {"linktype": "md switched"}},
            {"name": K.CODE},
            {"name": K.P},
            {"name": K.A, "data": {"linktype": "md switched"}},
            {"name": K.A, "data": {"linktype": "md switched"}},
            {"name": K.IMG, "data": {"linktype": "md switched"}},
            {"name": K.P}]
    },
    {
        "name": "parenthesis",
        "md": "\\((\\))\n",
        "tokens": [{"name": "paragraph_line"},
            {"name": "opening_parenthesis"},
            {"name": "closing_parenthesis"},
            {"name": "empty_line"},
            {"name": "endoffile"}],
        "nodes": [{"name": K.BODY}, {"name": K.P}, {"name": K.EMPTY_LINE}]
    },
    {
        "name": "double and single inline code",
        "md": "hamedi is ``coding`` with hamedi\nhamedi `` includes`in code`` 0\nhamedi ``includes`in code`` 1\nhamedi `codes` nothing\nhamedi``codes``nothing\n   ` hmid` or `not``",
        "tokens": [{"name": "paragraph_line"},
            {"name": "double_inline_code"},
            {"name": "double_inline_code"},
            {"name": "paragraph_line"},
            {"name": "double_inline_code"},
            {"name": "inline_code"},
            {"name": "double_inline_code"},
            {"name": "paragraph_line"},
            {"name": "double_inline_code"},
            {"name": "inline_code"},
            {"name": "double_inline_code"},
            {"name": "paragraph_line"},
            {"name": "inline_code"},
            {"name": "inline_code"},
            {"name": "paragraph_line"},
            {"name": "double_inline_code"},
            {"name": "double_inline_code"},
            {"name": "paragraph_line"},
            {"name": "inline_code"},
            {"name": "inline_code"},
            {"name": "inline_code"},
            {"name": "double_inline_code"}],
        "nodes": [{"name": K.BODY},
            {"name": K.P},
            {"name": K.CODE, "type":"double"},
            {"name": K.CODE, "type":"double"},
            {"name": K.CODE, "type":"double"},
            {"name": K.CODE, "type":"single"},
            {"name": K.CODE, "type":"double"},
            {"name": K.CODE, "type":"single"},
            {"name": K.CODE, "type":"single"}]
    }
]

class test_ast_tokenizer(unittest.TestCase):
    def test_cases(self):
        for c in TEST_CASES:
            with self.subTest(c = c["name"]):
                for markdown in (c["md"] if isinstance(c["md"], list) else [c["md"]]):
                    # if c["name"] == "unordered list":
                    #     print(*tokenize(markdown), sep="\n")
                    #     show(parse(markdown))
                    tokens = list(t for t in tokenize(markdown) if t.name != "text") # ignoring text tokens for now
                    for i, (tok, truetok) in enumerate(zip(tokens, c["tokens"])):
                        if "name" in truetok: self.assertEqual(tok.name, truetok["name"], (i, tokens))
                        if "data" in truetok: self.assertEqual(tok.data, truetok["data"], (i, tokens))
                    head = parse(markdown)
                    nodes = (n for n in walk(head) if n.k is not K.TEXT)
                    for i, (n, trueNode) in enumerate(zip(nodes, c["nodes"])):
                        if "name" in trueNode: self.assertEqual(n.k, trueNode["name"], (i, tokens, list(walk(head))))
                        if "data" in trueNode:
                            for k,v in trueNode["data"].items(): self.assertEqual(v, n.data[k], (i, tokens, list(walk(head))))
                    # check ast integrity
                    for node in walk(head):
                        if node.children:
                            for child in node.children:
                                self.assertIs(node, child.parent)
                        if node.parent: self.assertTrue(any(node is c for c in node.parent.children))
                        self.assertNotEqual(node.name, "bolditalic") # all bold italic nodes should be replaced by italic and bold nodes after treeification
                        if node.parent and node.parent.start and node.start: self.assertLessEqual(node.parent.start, node.start)
                        if node.parent and node.parent.end and node.end: self.assertGreaterEqual(node.parent.end, node.end)
                    
                    # head2 = parse(markdown)
                    # show(head2)
                    # print(serialize(head2, markdown))

class test_css_tokenizer(unittest.TestCase):
    def test_all(self):
        with open(Path(__file__).parent / "test.css", "r") as f: css = f.read()
        tree = tokenizeCSS(css)

        for node in walk(tree):
            if node.children:
                for child in node.children:
                    self.assertIs(node, child.parent)
            if node.parent: self.assertTrue(any(node is c for c in node.parent.children))
            self.assertIs(node.status, Status.CLOSED)

        # show(tree)
        # from pprint import pprint
        # pprint(css_to_dict(tree))

if  __name__ == "__main__": unittest.main()